version: '3.8'

services:

  migrate:
    image: migrate/migrate
    networks:
      - tender_network
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:root@postgres:5432/tender?sslmode=disable", "up" ]
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    container_name: tender_postgres
    image: postgres
    environment:
      POSTGRES_DB: tender
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_SSL_MODE: disable
    volumes:
      - tender_postgres_volume:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - tender_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d tender" ]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    container_name: tender-backend
    build: .
    ports:
      - "8888:8888"
    networks:
      - tender_network
    depends_on:
      redis-db:
        condition: service_healthy
      postgres-db:
        condition: service_healthy

  redis-db:
    container_name: cache-storage
    image: redis 
    ports:
      - "6378:6378"
    networks:
      - tender_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tender_network:
    driver: bridge

volumes:
  tender_postgres_volume:
