version: '3.8'

services:

  migrate:
    image: migrate/migrate
    networks:
      - asrlan
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:ebot@postgres:5432/asrlanmono?sslmode=disable", "up" ]
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ebot
      PGDATA: /data/postgres
      POSTGRES_DB: asrlanmono
    volumes:
      - db:/databasedatadb/postgres
    ports:
      - "5332:5332"
    networks:
      - asrlan
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    networks:
      - asrlan
    depends_on:
      - redisdb

  redisdb:
    container_name: redisdb
    image: redis 
    ports:
      - "6378:6378"
    networks:
      - asrlan

networks:
  asrlan:
    driver: bridge

volumes:
  db:
